<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NOTA CHECKLIST #{{ $cl->id }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; font-size: 12px; color: #222 }
        .header { margin-bottom: 12px }
        table { width: 100%; border-collapse: collapse }
        th, td { border: 1px solid #ddd; padding: 8px; }
        th { background: #f7f7f7; }
        .right { text-align: right }
    </style>
</head>
<body>
    <div class="header">
        <h2>NOTA CHECKLIST #{{ $cl->id }}</h2>
        <div>Order: {{ $cl->order->invoice_code ?? $cl->order->id }}</div>
        <div>Pelanggan: {{ $cl->recipient_name }}</div>
        <div>Tanggal Pesanan: {{ \Carbon\Carbon::parse($cl->order->created_at)->format('d/m/Y H:i') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Produk</th>
                <th class="right">Qty</th>
                <th class="right">Checked</th>
            </tr>
        </thead>
        <tbody>
            @foreach($cl->order->orderItems as $oi)
            <tr>
                <td>{{ $oi->product_name }}</td>
                <td class="right">{{ $oi->qty }}</td>
                <td class="right">{{ $cl->items->where('product_id', $oi->product_id)->first()->qty_checked ?? 0 }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top:20px; font-size:11px; color:#666">Generated by Toko Utama POS System</div>
</body>
</html>